#!/bin/bash

# ==============================================================================
# CGP Master SSL - Автоматизация Let's Encrypt для CommuniGate Pro
# GitHub: https://raw.githubusercontent.com/saym101/update_cgp_cert/refs/heads/main/update_cgp_cert.sh
# ==============================================================================

# --- БЛОК НАСТРОЕК (ЗАПОЛНИТЕ СВОИМИ ДАННЫМИ) ---
EMAIL_ADMIN="admin@example.com"      # Аккаунт администратора CGP
EMAIL_REPORT="reports@example.com"   # Куда слать отчеты о работе
SMTP_PASS="YourSecurePassword"       # Пароль администратора CGP
IP_CGP="127.0.0.1"                   # IP сервера CommuniGate
CLI_PORT="8100"                      # Порт CLI CommuniGate (по умолчанию 8100)
SMTP_PORT="25"                       # Порт SMTP для отправки отчетов
HELO_HOST="example.com"           # HELO для SMTP сессии

# Настройки скрипта
CONFIG_ASSISTANT=true
EXIT_TIMEOUT=60
LOG_FILE="/var/log/update_cgp_cert.log"
REQUIRED_PACKAGES="certbot curl lsof openssl"

# --- РЕДАКТИРУЕМАЯ ТАБЛИЦА СТОП-КОМАНД ---
# Добавьте сюда службы, которые занимают 80 порт
declare -A CUSTOM_STOP=( ["apache2"]="systemctl stop apache2" ["nginx"]="systemctl stop nginx" ["caddy"]="systemctl stop caddy" )
declare -A CUSTOM_START=( ["apache2"]="systemctl start apache2" ["nginx"]="systemctl start nginx" ["caddy"]="systemctl start caddy" )

# --- ГЛОБАЛЬНЫЕ ПЕРЕМЕННЫЕ ---
REPORT_DATA=()
mkdir -p "$(dirname "$LOG_FILE")"

log_msg() { 
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >> "$LOG_FILE"
    REPORT_DATA+=("$1")
    [ -t 0 ] && echo -e "$1"
}

# --- ФУНКЦИЯ ОТПРАВКИ УВЕДОМЛЕНИЙ ---
send_notification() {
    [ -t 0 ] && return 0 
    
    local subject="SSL Report: $(hostname) - $(date +%F)"
    local temp_mail="/tmp/ssl_mail.txt"
    
    {
        echo "To: $EMAIL_REPORT"
        echo "From: $EMAIL_ADMIN"
        echo "Subject: $subject"
        echo "Content-Type: text/html; charset=UTF-8"
        echo ""
        echo "<html><body>"
        echo "<h2>SSL Update Report</h2><hr>"
        for line in "${REPORT_DATA[@]}"; do
            if [[ "$line" == *"[OK]"* ]]; then
                echo "<p style='color:green;'>$line</p>"
            elif [[ "$line" == *"[FAIL]"* ]] || [[ "$line" == *"[ERROR]"* ]]; then
                echo "<p style='color:red;'><b>$line</b></p>"
            else
                echo "<p>$line</p>"
            fi
        done
        echo "<hr><p>Generated by CGP Master Script: $(date)</p></body></html>"
    } > "$temp_mail"

    curl --url "smtp://$IP_CGP:$SMTP_PORT" \
         --mail-from "$EMAIL_ADMIN" \
         --mail-rcpt "$EMAIL_REPORT" \
         --upload-file "$temp_mail" \
         --user "$EMAIL_ADMIN:$SMTP_PASS" \
         --mail-auth "$EMAIL_ADMIN" \
         -k --silent --show-error >> "$LOG_FILE" 2>&1

    rm -f "$temp_mail"
}

# --- ОСНОВНЫЕ ФУНКЦИИ ---
smart_read() {
    local timeout=$EXIT_TIMEOUT
    local char=""
    echo -e "\n\e[36mWaiting for choice ($timeout sec)...\e[0m" >&2
    while [ $timeout -gt 0 ]; do
        if read -t 1 -n 1 char; then echo "$char"; return 0; fi
        ((timeout--))
        echo -ne "\r\e[33mTime left: $timeout sec...\e[0m " >&2
    done
    echo "TIMEOUT_EXIT"
}

fetch_domains_from_cgp() {
    local raw_list
    raw_list=$(curl -s -u "$EMAIL_ADMIN:$SMTP_PASS" -k "http://$IP_CGP:$CLI_PORT/cli/?command=listdomains")
    [ $? -ne 0 ] || [ -z "$raw_list" ] && return 1
    DOMAINS_BASE=$(echo "$raw_list" | sed 's/[^a-zA-Z0-9.-]/ /g' | xargs)
    return 0
}

get_port_owner() { lsof -i :80 -sTCP:LISTEN -t | xargs ps -o comm= -p 2>/dev/null | head -n 1 | tr -d ' '; }

task_get_certs() {
    log_msg ">>> Getting certificates..."
    fetch_domains_from_cgp || return 1
    local owner=$(get_port_owner)
    local services_to_start=()
    
    if [ -n "$owner" ]; then
        if [[ -n "${CUSTOM_STOP[$owner]}" ]]; then
            log_msg "Stopping $owner..."
            ${CUSTOM_STOP[$owner]} >> "$LOG_FILE" 2>&1
            services_to_start+=("$owner")
        fi
    fi

    for domain in $DOMAINS_BASE; do
        if certbot certonly --standalone -d "mail.$domain" --key-type rsa --rsa-key-size 2048 --non-interactive --agree-tos --email "$EMAIL_ADMIN" >> "$LOG_FILE" 2>&1; then
            log_msg "[OK] mail.$domain cert received"
        else
            log_msg "[FAIL] mail.$domain certbot error"
        fi
    done

    for svc in "${services_to_start[@]}"; do
        ${CUSTOM_START[$svc]} >> "$LOG_FILE" 2>&1
    done
}

task_install_to_cgp() {
    log_msg ">>> Installing to CommuniGate..."
    fetch_domains_from_cgp || return 1
    for domain in $DOMAINS_BASE; do
        local path="/etc/letsencrypt/live/mail.$domain"
        if [ -d "$path" ]; then
            key=$(openssl rsa -in "$path/privkey.pem" -traditional 2>/dev/null | grep -v '\-\-' | tr -d '\n\r ')
            crt=$(cat "$path/cert.pem" | grep -v '\-\-' | tr -d '\n\r ')
            chain=$(cat "$path/fullchain.pem" | grep -v '\-\-' | tr -d '\n\r ')
            
            CMD="command=updatedomainsettings ${domain} {PrivateSecureKey=[${key}];SecureCertificate=[${crt}];CAChain=[${chain}];}"
            resp=$(curl -s -u "$EMAIL_ADMIN:$SMTP_PASS" -k "http://$IP_CGP:$CLI_PORT/cli/" --data-urlencode "$CMD")
            
            if [ $? -eq 0 ] && [[ ! "$resp" =~ "ERROR" ]]; then
                log_msg "[OK] $domain updated successfully"
            else
                log_msg "[FAIL] $domain CLI error ($resp)"
            fi
        fi
    done
}

task_cleanup_smart() {
    log_msg ">>> Cleanup expired certs..."
    local cert_output=$(certbot certificates 2>/dev/null)
    local cert_list=$(echo "$cert_output" | grep "Certificate Name" | awk '{print $3}')
    for cert in $cert_list; do
        local exp_date=$(echo "$cert_output" | sed -n "/Certificate Name: $cert/,/Expiry Date/p" | grep "Expiry Date" | awk '{print $3}')
        local exp_sec=$(date -d "$exp_date" +%s 2>/dev/null)
        if [ -n "$exp_sec" ] && [ "$exp_sec" -lt "$(date +%s)" ]; then
            log_msg "[EXPIRED] Removing $cert..."
            certbot delete --non-interactive --cert-name "$cert" >> "$LOG_FILE" 2>&1
        fi
    done
}

# --- EXECUTION ---
if [ -t 0 ]; then
    while true; do
        echo -e "\n1) FULL CYCLE\n2) Get Certs\n3) Install to CGP\n4) Cleanup\n0) Exit"
        ch=$(smart_read)
        case "$ch" in
            1) task_get_certs; task_install_to_cgp; task_cleanup_smart ;;
            0) exit 0 ;;
            TIMEOUT_EXIT) exit 0 ;;
        esac
    done
else
    task_get_certs
    task_install_to_cgp
    task_cleanup_smart
    send_notification
fi
